### ISSUE TITLE
请求搬运至商店适配思源新版本

### ISSUE THREAD

**Issue by chenshinshi** [UserZYF/chuizi#2]
作者您好！非常喜欢您的主题，十分精致有创意，了解到您工作忙已经不再维护和更新主题了，想请求您允许我搬运上架至思源适配新的版本。再次非常感谢您！

**Comment by UserZYF** [comment]
好，十分期待，到时候为你点赞😁



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月22日(周四) 下午5:40
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [UserZYF/chuizi] 请求搬运至商店适配思源新版本 (Issue #2)




 
作者您好！非常喜欢您的主题，十分精致有创意，了解到您工作忙已经不再维护和更新主题了，想请求您允许我搬运上架至思源适配新的版本。再次非常感谢您！
